<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Wasm2Cs.Runtime/Wasm2Cs.Runtime.csproj" />
    <ProjectReference Include="../../src/Wasm2Cs.Generator/Wasm2Cs.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <Wasm Include="Arithmetic.wasm" />
    <Wasm Include="../Floating/Floating.wasm" />
    <Compile Include="../Floating/FloatingChecks.cs" Link="FloatingChecks.cs" />
    <Wasm Include="../CAlgorithms/Algorithms.wasm" />
    <Wasm Include="../Host/Host.wasm" />
    <Compile Include="../Host/HostChecks.cs" Link="HostChecks.cs" />
  </ItemGroup>
  <Import Project="../../build/Wasm2Cs.targets" />
</Project>
