<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Wasm2Cs.Generator/Wasm2Cs.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <Wasm Include="Arithmetic.wasm" />
  </ItemGroup>
  <Import Project="../../build/Wasm2Cs.targets" />
</Project>
