using System.Globalization;
using System.Text;
namespace Wasm2Cs;
internal static class CSharpEmitter
{
    public static string Emit(Module module, string className)
    {
        var source = new StringBuilder("// <auto-generated/>\n#pragma warning disable CS0219, CS0414, CS0162, CS0164 // Valid WASM may contain unused values/globals, unreachable code and labels.\nnamespace Wasm2Cs.Generated\n{\n");
        source.Append("public sealed class @").Append(className).Append("\n{\n");
        source.Append(I32Operations.Helpers);
        if (module.Memory != null) source.Append(MemoryOperations.Helpers.Replace("__WASM_MAX_PAGES__", module.Memory.Maximum.ToString(CultureInfo.InvariantCulture)));
        for(int g=0;g<module.Globals.Count;g++) source.Append($"    private int __wasm_G{g};\n");
        for (int i=0;i<module.Imports.Count;i++)
        {
            var signature = module.FunctionSignature(i);
            string result = signature.Results == 0 ? "void" : "int";
            string parameters = string.Join(", ", Enumerable.Range(0,signature.Parameters).Select(p => $"int v{p}"));
            // Base64 keeps arbitrary UTF-8 import names out of C# syntax and comments.
            source.Append($"    // Import {i}: module/name UTF-8 base64 {Convert.ToBase64String(Encoding.UTF8.GetBytes(module.Imports[i].ModuleName))}/{Convert.ToBase64String(Encoding.UTF8.GetBytes(module.Imports[i].Name))}\n");
            source.Append($"    public delegate {result} __wasm_Import{i}({parameters});\n");
            source.Append($"    private readonly __wasm_Import{i} __wasm_host{i};\n");
            source.Append($"    private {result} __wasm_F{i}({parameters}) {{ {(signature.Results == 0 ? "" : "return ")}__wasm_host{i}({string.Join(", ",Enumerable.Range(0,signature.Parameters).Select(p => $"v{p}"))}); }}\n");
        }
        source.Append($"    public @{className}({string.Join(", ",Enumerable.Range(0,module.Imports.Count).Select(i => $"__wasm_Import{i} import{i}"))})\n    {{\n");
        for (int i=0;i<module.Imports.Count;i++) source.Append($"        __wasm_host{i} = import{i} ?? throw new global::System.ArgumentNullException(\"import{i}\");\n");
        if (module.Memory != null) source.Append($"        __wasm_memory = new byte[{module.Memory.Minimum*65536}];\n");
        for(int g=0;g<module.Globals.Count;g++) source.Append($"        __wasm_G{g} = {module.Globals[g].InitialValue.ToString(CultureInfo.InvariantCulture)};\n");
        foreach(var data in module.Data) source.Append($"        WriteMemory({data.Offset}u, global::System.Convert.FromBase64String(\"{Convert.ToBase64String(data.Bytes)}\"));\n");
        if (module.Start.HasValue) source.Append($"        __wasm_F{module.Start.Value}();\n");
        source.Append("    }\n");
        for (int i=0;i<module.Bodies.Count;i++)
        {
            var function = module.Bodies[i];
            source.Append("    private ").Append(function.Signature.Results == 0 ? "void" : "int")
                .Append(" __wasm_F").Append(i + module.Imports.Count).Append('(')
                .Append(string.Join(", ", Enumerable.Range(0, function.Signature.Parameters).Select(p => $"int v{p}")))
                .Append(")\n    {\n").Append(EmitBody(module, function)).Append("    }\n");
        }
        foreach (var export in module.Exports)
        {
            byte kind = module.ExportKinds[export.Key];
            if (kind == 2) continue; // Memory exports use the copy-based host API.
            if (kind == 3)
            {
                source.Append($"    public int @{export.Key} {{ get {{ return __wasm_G{export.Value}; }}");
                if (module.Globals[export.Value].Mutable) source.Append($" set {{ __wasm_G{export.Value} = value; }}");
                source.Append(" }\n");
                continue;
            }
            var exportSignature = module.FunctionSignature(export.Value);
            source.Append("    public ").Append(exportSignature.Results == 0 ? "void" : "int")
                .Append(" @").Append(export.Key).Append('(');
            source.Append(string.Join(", ", Enumerable.Range(0, exportSignature.Parameters).Select(i => $"int v{i}")));
            source.Append(")\n    {\n        ").Append(exportSignature.Results == 0 ? "" : "return ")
                .Append("__wasm_F").Append(export.Value).Append('(')
                .Append(string.Join(", ", Enumerable.Range(0, exportSignature.Parameters).Select(p => $"v{p}")))
                .Append(");\n    }\n");
        }
        return source.Append("}\n}\n").ToString();
    }
    private sealed class Control(byte opcode, List<string> values, string result, int label)
    {
        public byte Opcode = opcode;
        public List<string> Values = values;
        public string Result = result;
        public string Start = $"L{label}_start", End = $"L{label}_end", Else = $"L{label}_else";
        public bool ElseSeen;
    }

    private static string EmitBody(Module module, Function function)
    {
        var code = new StringBuilder();
        var declarations = new StringBuilder();
        for (int i = function.Signature.Parameters; i < function.Locals; i++)
            declarations.Append($"        int v{i} = 0;\n");
        var stack = new List<string>();
        int temporary = 0, label = 0;
        string Temp()
        {
            string name = $"s{temporary++}";
            declarations.Append($"        int {name} = 0;\n");
            return name;
        }
        var controls = new List<Control> { new Control(0xff, new List<string>(), function.Signature.Results == 1 ? Temp() : "", label++) };
        void Line(string text) => code.Append("        ").Append(text).Append('\n');
        string Pop()
        {
            // Validated unreachable code may consume the polymorphic stack bottom.
            if (stack.Count == controls[controls.Count-1].Values.Count) return "0";
            string value = stack[stack.Count-1]; stack.RemoveAt(stack.Count-1); return value;
        }
        void Push(string expression) { string value = Temp(); Line($"{value} = {expression};"); stack.Add(value); }
        void Restore(Control frame) { stack = new List<string>(frame.Values); }
        void Branch(Control target, string value)
        {
            if (target.Opcode != 0x03 && target.Result != "") Line($"{target.Result} = {value};");
            Line($"goto {(target.Opcode == 0x03 ? target.Start : target.End)};");
        }
        foreach (var instruction in function.Instructions)
        {
            var current = controls[controls.Count-1];
            Control Target(int depth) => controls[controls.Count-1-depth];
            switch (instruction.Opcode)
            {
                case 0x02: case 0x03: case 0x04:
                    string condition = instruction.Opcode == 0x04 ? Pop() : "";
                    var frame = new Control(instruction.Opcode,new List<string>(stack),instruction.Operand == 1 ? Temp() : "",label++);
                    controls.Add(frame);
                    if (instruction.Opcode == 0x03) Line(frame.Start + ": ;");
                    if (instruction.Opcode == 0x04) Line($"if ({condition} == 0) goto {frame.Else};");
                    break;
                case 0x05:
                    if (current.Result != "") Line($"{current.Result} = {Pop()};");
                    Line($"goto {current.End};"); Line(current.Else + ": ;");
                    current.ElseSeen = true; Restore(current);
                    break;
                case 0x0b:
                    if (current.Result != "") Line($"{current.Result} = {Pop()};");
                    if (current.Opcode == 0x04 && !current.ElseSeen) Line(current.Else + ": ;");
                    Line(current.End + ": ;");
                    Restore(current);
                    controls.RemoveAt(controls.Count-1);
                    if (current.Opcode == 0xff) Line(current.Result == "" ? "return;" : $"return {current.Result};");
                    else if (current.Result != "") stack.Add(current.Result);
                    break;
                case 0x00: Line("throw new TrapException(TrapKind.Unreachable);"); Restore(current); break;
                case 0x0c: case 0x0d:
                    string branchCondition = instruction.Opcode == 0x0d ? Pop() : "";
                    var target = Target(instruction.Operand);
                    string value = target.Opcode != 0x03 && target.Result != "" ? Pop() : "0";
                    if (instruction.Opcode == 0x0d)
                    {
                        Line($"if ({branchCondition} != 0) {{"); Branch(target,value); Line("}");
                        if (target.Opcode != 0x03 && target.Result != "") stack.Add(value);
                    }
                    else { Branch(target,value); Restore(current); }
                    break;
                case 0x0e:
                    string selector = Pop();
                    var targets = instruction.Targets!;
                    var first = Target(targets[0]);
                    string branchValue = first.Opcode != 0x03 && first.Result != "" ? Pop() : "0";
                    Line($"switch (unchecked((uint){selector})) {{");
                    for(int i=0;i<targets.Length;i++)
                    {
                        Line(i == targets.Length-1 ? "default:" : $"case {i}u:");
                        Branch(Target(targets[i]),branchValue);
                    }
                    Line("}"); Restore(current); break;
                case 0x0f:
                    Line(function.Signature.Results == 0 ? "return;" : $"return {Pop()};");
                    Restore(current);
                    break;
                case 0x10:
                    var signature = module.FunctionSignature(instruction.Operand);
                    var arguments = new string[signature.Parameters];
                    for(int p=arguments.Length-1;p>=0;p--) arguments[p] = Pop();
                    string call = $"__wasm_F{instruction.Operand}({string.Join(", ",arguments)})";
                    if (signature.Results == 1) Push(call); else Line(call+";");
                    break;
                case 0x1a: Pop(); break;
                case 0x1b:
                    string selected = Pop(), b = Pop(), a = Pop();
                    Push($"{selected} != 0 ? {a} : {b}"); break;
                case 0x20: Push($"v{instruction.Operand}"); break;
                case 0x21: case 0x22:
                    string localValue = Pop();
                    Line($"v{instruction.Operand} = {localValue};");
                    if (instruction.Opcode == 0x22) stack.Add(localValue);
                    break;
                case 0x41: Push(instruction.Operand.ToString(CultureInfo.InvariantCulture)); break;
                case 0x23: Push($"__wasm_G{instruction.Operand}"); break;
                case 0x24: Line($"__wasm_G{instruction.Operand} = {Pop()};"); break;
                case 0x28: case 0x2c: case 0x2d: case 0x2e: case 0x2f:
                    Push($"__wasm_Load({Pop()}, {instruction.Immediate}u, {MemoryOperations.Width(instruction.Opcode)}, {(instruction.Opcode == 0x2c || instruction.Opcode == 0x2e ? "true" : "false")})"); break;
                case 0x36: case 0x3a: case 0x3b:
                    string stored = Pop(), address = Pop();
                    Line($"__wasm_Store({address}, {stored}, {instruction.Immediate}u, {MemoryOperations.Width(instruction.Opcode)});"); break;
                case 0x3f: Push("__wasm_memory.Length / 65536"); break;
                case 0x40: Push($"__wasm_Grow({Pop()})"); break;
                default:
                    int arity = I32Operations.Arity(instruction.Opcode);
                    if (arity == 0) break;
                    string right = arity == 2 ? Pop() : "";
                    Push(I32Operations.Expression(instruction.Opcode, Pop(), right));
                    break;
            }
        }
        return declarations.ToString() + code.ToString();
    }
}
