using System.Globalization;
using System.Text;
namespace Wasm2Cs;
internal static class CSharpEmitter
{
    public static string Emit(Module module, string className)
    {
        var source = new StringBuilder("// <auto-generated/>\n#pragma warning disable CS0219, CS0162, CS0164 // Valid WASM may contain unused values, unreachable code and labels.\nnamespace Wasm2Cs.Generated\n{\n");
        source.Append("public sealed class @").Append(className).Append("\n{\n");
        source.Append(I32Operations.Helpers);
        foreach (var export in module.Exports)
        {
            var function = module.Bodies[export.Value];
            source.Append("    public ").Append(function.Signature.Results == 0 ? "void" : "int")
                .Append(" @").Append(export.Key).Append('(');
            source.Append(string.Join(", ", Enumerable.Range(0, function.Signature.Parameters).Select(i => $"int v{i}")));
            source.Append(")\n    {\n").Append(EmitBody(function)).Append("    }\n");
        }
        return source.Append("}\n}\n").ToString();
    }
    private sealed class Control(byte opcode, List<string> values, string result, int label)
    {
        public byte Opcode = opcode;
        public List<string> Values = values;
        public string Result = result;
        public string Start = $"L{label}_start", End = $"L{label}_end", Else = $"L{label}_else";
        public bool ElseSeen;
    }

    private static string EmitBody(Function function)
    {
        var code = new StringBuilder();
        var declarations = new StringBuilder();
        for (int i = function.Signature.Parameters; i < function.Locals; i++)
            declarations.Append($"        int v{i} = 0;\n");
        var stack = new List<string>();
        int temporary = 0, label = 0;
        string Temp()
        {
            string name = $"s{temporary++}";
            declarations.Append($"        int {name} = 0;\n");
            return name;
        }
        var controls = new List<Control> { new Control(0xff, new List<string>(), function.Signature.Results == 1 ? Temp() : "", label++) };
        void Line(string text) => code.Append("        ").Append(text).Append('\n');
        string Pop()
        {
            // Validated unreachable code may consume the polymorphic stack bottom.
            if (stack.Count == controls[controls.Count-1].Values.Count) return "0";
            string value = stack[stack.Count-1]; stack.RemoveAt(stack.Count-1); return value;
        }
        void Push(string expression) { string value = Temp(); Line($"{value} = {expression};"); stack.Add(value); }
        void Restore(Control frame) { stack = new List<string>(frame.Values); }
        void Branch(Control target, string value)
        {
            if (target.Opcode != 0x03 && target.Result != "") Line($"{target.Result} = {value};");
            Line($"goto {(target.Opcode == 0x03 ? target.Start : target.End)};");
        }
        foreach (var instruction in function.Instructions)
        {
            var current = controls[controls.Count-1];
            Control Target(int depth) => controls[controls.Count-1-depth];
            switch (instruction.Opcode)
            {
                case 0x02: case 0x03: case 0x04:
                    string condition = instruction.Opcode == 0x04 ? Pop() : "";
                    var frame = new Control(instruction.Opcode,new List<string>(stack),instruction.Operand == 1 ? Temp() : "",label++);
                    controls.Add(frame);
                    if (instruction.Opcode == 0x03) Line(frame.Start + ": ;");
                    if (instruction.Opcode == 0x04) Line($"if ({condition} == 0) goto {frame.Else};");
                    break;
                case 0x05:
                    if (current.Result != "") Line($"{current.Result} = {Pop()};");
                    Line($"goto {current.End};"); Line(current.Else + ": ;");
                    current.ElseSeen = true; Restore(current);
                    break;
                case 0x0b:
                    if (current.Result != "") Line($"{current.Result} = {Pop()};");
                    if (current.Opcode == 0x04 && !current.ElseSeen) Line(current.Else + ": ;");
                    Line(current.End + ": ;");
                    Restore(current);
                    controls.RemoveAt(controls.Count-1);
                    if (current.Opcode == 0xff) Line(current.Result == "" ? "return;" : $"return {current.Result};");
                    else if (current.Result != "") stack.Add(current.Result);
                    break;
                case 0x00: Line("throw new TrapException(TrapKind.Unreachable);"); Restore(current); break;
                case 0x0c: case 0x0d:
                    string branchCondition = instruction.Opcode == 0x0d ? Pop() : "";
                    var target = Target(instruction.Operand);
                    string value = target.Opcode != 0x03 && target.Result != "" ? Pop() : "0";
                    if (instruction.Opcode == 0x0d)
                    {
                        Line($"if ({branchCondition} != 0) {{"); Branch(target,value); Line("}");
                        if (target.Opcode != 0x03 && target.Result != "") stack.Add(value);
                    }
                    else { Branch(target,value); Restore(current); }
                    break;
                case 0x0e:
                    string selector = Pop();
                    var targets = instruction.Targets!;
                    var first = Target(targets[0]);
                    string branchValue = first.Opcode != 0x03 && first.Result != "" ? Pop() : "0";
                    Line($"switch (unchecked((uint){selector})) {{");
                    for(int i=0;i<targets.Length;i++)
                    {
                        Line(i == targets.Length-1 ? "default:" : $"case {i}u:");
                        Branch(Target(targets[i]),branchValue);
                    }
                    Line("}"); Restore(current); break;
                case 0x0f:
                    Line(function.Signature.Results == 0 ? "return;" : $"return {Pop()};");
                    Restore(current);
                    break;
                case 0x1a: Pop(); break;
                case 0x1b:
                    string selected = Pop(), b = Pop(), a = Pop();
                    Push($"{selected} != 0 ? {a} : {b}"); break;
                case 0x20: Push($"v{instruction.Operand}"); break;
                case 0x21: case 0x22:
                    string localValue = Pop();
                    Line($"v{instruction.Operand} = {localValue};");
                    if (instruction.Opcode == 0x22) stack.Add(localValue);
                    break;
                case 0x41: Push(instruction.Operand.ToString(CultureInfo.InvariantCulture)); break;
                default:
                    int arity = I32Operations.Arity(instruction.Opcode);
                    if (arity == 0) break;
                    string right = arity == 2 ? Pop() : "";
                    Push(I32Operations.Expression(instruction.Opcode, Pop(), right));
                    break;
            }
        }
        return declarations.ToString() + code.ToString();
    }
}
