using System.Globalization;
using System.Text;

namespace Wasm2Cs;

public sealed class WasmException(string message) : Exception(message);

/// <summary>Translates a deliberately small, validated subset of WebAssembly into C#.</summary>
public static class Transpiler
{
    public static string Translate(byte[] wasm, string className)
    {
        if (!IsIdentifier(className))
            throw new WasmException("The WASM filename must be an ASCII C# identifier.");
        var reader = new Reader(wasm);
        foreach (var expected in new byte[] { 0, 97, 115, 109, 1, 0, 0, 0 })
            if (reader.Byte() != expected) throw new WasmException("Invalid WASM magic or version.");

        var types = new List<Signature>();
        var functions = new List<int>();
        var exports = new Dictionary<string, int>(StringComparer.Ordinal);
        var bodies = new List<Reader>();
        byte previous = 0;
        while (!reader.End)
        {
            var id = reader.Byte();
            var section = reader.Slice(reader.Count());
            if (id == 0)
            {
                section.Name(); // Custom sections still require a well-formed name.
                continue;
            }
            if (id <= previous) throw new WasmException("Duplicate or out-of-order section.");
            previous = id;
            switch (id)
            {
                case 1:
                    for (int i = 0, count = section.Count(); i < count; i++)
                    {
                        if (section.Byte() != 0x60) throw new WasmException("Only function types are supported.");
                        int parameters = section.Count();
                        for (int p = 0; p < parameters; p++) section.I32Type();
                        int results = section.Count();
                        if (results > 1) throw new WasmException("Multiple results are not supported.");
                        if (results == 1) section.I32Type();
                        types.Add(new(parameters, results));
                    }
                    break;
                case 3:
                    for (int i = 0, count = section.Count(); i < count; i++)
                        functions.Add(section.Count());
                    break;
                case 7:
                    for (int i = 0, count = section.Count(); i < count; i++)
                    {
                        string name = section.Name();
                        if (section.Byte() != 0) throw new WasmException("Only function exports are supported.");
                        if (!IsIdentifier(name) || name == className)
                            throw new WasmException($"Export '{name}' cannot be represented as a C# method name.");
                        if (!exports.TryAdd(name, section.Count())) throw new WasmException("Duplicate export name.");
                    }
                    break;
                case 10:
                    for (int i = 0, count = section.Count(); i < count; i++)
                        bodies.Add(section.Slice(section.Count()));
                    break;
                default:
                    throw new WasmException($"Unsupported WASM section {id}.");
            }
            section.RequireEnd();
        }
        if (functions.Count != bodies.Count) throw new WasmException("Function and code counts differ.");
        var implementations = new List<string>();
        for (int i = 0; i < functions.Count; i++)
        {
            if (functions[i] >= types.Count) throw new WasmException("Invalid function type index.");
            implementations.Add(TranslateBody(bodies[i], types[functions[i]]));
        }

        var source = new StringBuilder("// <auto-generated/>\n#pragma warning disable CS0219 // WASM may discard locals and stack values.\nnamespace Wasm2Cs.Generated\n{\n");
        source.Append("public static class @").Append(className).Append("\n{\n");
        foreach (var export in exports)
        {
            if (export.Value >= functions.Count) throw new WasmException("Invalid exported function index.");
            var signature = types[functions[export.Value]];
            source.Append("    public static ").Append(signature.Results == 0 ? "void" : "int")
                .Append(" @").Append(export.Key).Append('(');
            source.Append(string.Join(", ", Enumerable.Range(0, signature.Parameters).Select(i => $"int v{i}")));
            source.Append(")\n    {\n").Append(implementations[export.Value]).Append("    }\n");
        }
        return source.Append("}\n}\n").ToString();
    }

    private static string TranslateBody(Reader body, Signature signature)
    {
        var code = new StringBuilder();
        int locals = signature.Parameters;
        for (int i = 0, groups = body.Count(); i < groups; i++)
        {
            int count = body.Count();
            body.I32Type();
            if ((long)locals + count > 100_000) throw new WasmException("Too many locals (limit: 100000).");
            for (int j = 0; j < count; j++) code.Append($"        int v{locals++} = 0;\n");
        }
        var stack = new Stack<string>();
        int temporary = 0;
        bool returned = false;
        string Pop() => stack.Count == 0 ? throw new WasmException("Operand stack underflow.") : stack.Pop();
        void Push(string expression)
        {
            string name = $"s{temporary++}";
            code.Append($"        int {name} = {expression};\n");
            stack.Push(name);
        }
        while (!body.End)
        {
            byte opcode = body.Byte();
            if (opcode == 0x0b)
            {
                body.RequireEnd();
                if (!returned)
                {
                    if (stack.Count != signature.Results) throw new WasmException("Invalid result stack height.");
                    code.Append(signature.Results == 0 ? "        return;\n" : $"        return {Pop()};\n");
                }
                return code.ToString();
            }
            if (returned) throw new WasmException("Instructions following return are not supported.");
            switch (opcode)
            {
                case 0x01: break; // nop
                case 0x0f:
                    code.Append(signature.Results == 0 ? "        return;\n" : $"        return {Pop()};\n");
                    returned = true;
                    break;
                case 0x1a: Pop(); break; // drop
                case 0x20:
                case 0x21:
                case 0x22:
                    int index = body.Count();
                    if (index >= locals) throw new WasmException("Invalid local index.");
                    if (opcode == 0x20) Push($"v{index}");
                    else
                    {
                        string value = Pop();
                        code.Append($"        v{index} = {value};\n");
                        if (opcode == 0x22) stack.Push(value);
                    }
                    break;
                case 0x41: Push(body.SignedI32().ToString(CultureInfo.InvariantCulture)); break;
                case 0x6a:
                case 0x6b:
                case 0x6c:
                    string right = Pop(), left = Pop();
                    string operation = opcode == 0x6a ? "+" : opcode == 0x6b ? "-" : "*";
                    Push($"unchecked({left} {operation} {right})");
                    break;
                default: throw new WasmException($"Unsupported WASM opcode 0x{opcode:x2}.");
            }
        }
        throw new WasmException("Function body is missing end.");
    }

    private static bool IsIdentifier(string name) => name.Length > 0 &&
        (char.IsAsciiLetter(name[0]) || name[0] == '_') &&
        name.All(c => char.IsAsciiLetterOrDigit(c) || c == '_');

    private sealed record Signature(int Parameters, int Results);

    private sealed class Reader(byte[] bytes, int start = 0, int? end = null)
    {
        private int position = start;
        private readonly int limit = end ?? bytes.Length;
        public bool End => position == limit;
        public byte Byte() => position < limit ? bytes[position++] : throw new WasmException("Unexpected end of WASM binary.");
        public void RequireEnd() { if (!End) throw new WasmException("Trailing bytes in section or function."); }
        public void I32Type() { if (Byte() != 0x7f) throw new WasmException("Only i32 values are supported."); }
        private uint Leb(bool signed)
        {
            uint value = 0;
            for (int i = 0; i < 5; i++)
            {
                byte b = Byte();
                if (i == 4 && (signed ? (b & 0x78) != 0 && (b & 0x78) != 0x78 : (b & 0x70) != 0))
                    throw new WasmException("LEB128 integer exceeds 32 bits.");
                value |= (uint)(b & 0x7f) << (7 * i);
                if ((b & 0x80) == 0)
                {
                    if (signed && i < 4 && (b & 0x40) != 0) value |= uint.MaxValue << (7 * (i + 1));
                    return value;
                }
            }
            throw new WasmException("LEB128 integer is too long.");
        }
        public int SignedI32() => unchecked((int)Leb(true));
        public int Count()
        {
            uint value = Leb(false);
            if (value > int.MaxValue) throw new WasmException("Length or index exceeds implementation limit.");
            return (int)value;
        }
        public Reader Slice(int length)
        {
            if (length > limit - position) throw new WasmException("Section or body extends past binary boundary.");
            var result = new Reader(bytes, position, position + length);
            position += length;
            return result;
        }
        public string Name()
        {
            var text = Slice(Count());
            try { return new UTF8Encoding(false, true).GetString(bytes, text.position, text.limit - text.position); }
            catch (DecoderFallbackException) { throw new WasmException("Invalid UTF-8 name."); }
        }
    }
}
